trigger:
  branches:
    include:
      - main

variables:
  dockerRegistryServiceConnection: 'YOUR-ACR-SERVICE-CONNECTION'
  imageRepository: 'my-dotnet-app'
  containerRegistry: 'youracrname.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  azureSubscription: 'YOUR-AZURE-RM-CONNECTION'
  appName: 'your-app-name'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: buildAndPush
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: BuildAndPush
  jobs:
  - deployment: DeployWebApp
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appName)
              containers: |
                $(containerRegistry)/$(imageRepository):latest
